version: '3.9'

name: partstracker

services:
  partstracker.mongo:
    image: mongo
    container_name: PartsTracker.MongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1qazXSW@
    ports:
      - 27017:27017
    volumes:
      - ../.containers/mongodb/data:/data/db

  partstracker.mongo-express:
    image: mongo-express
    container_name: PartsTracker.MongoExpress
    restart: always
    ports:
      - 5081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1qazXSW@
      ME_CONFIG_MONGODB_URL: mongodb://root:1qazXSW%40@partstracker.mongo:27017/
      ME_CONFIG_BASICAUTH: false

  partstracker.seq:
    image: datalust/seq:latest
    container_name: PartsTracker.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  partstracker.redis:
    image: redis:latest
    container_name: PartsTracker.Redis
    restart: always
    ports:
      - 6379:6379

  partstracker.api:
    image: ${DOCKER_REGISTRY-}partstrackerapi
    container_name: PartsTracker.Api
    build:
      context: ../server
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - MONGO_USER=root
      - MONGO_PASSWORD=1qazXSW@
      - MONGO_PATH=@partstracker.mongo:27017
      - MONGO_DB=assessment_project
      - REDIS_HOST=partstracker.redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1qazXSW@
      - PORT=5000
      - SEQ_HOST=partstracker.seq
      - SEQ_PORT=5341
      - SEQ_API_KEY=
    depends_on:
      - partstracker.mongo
      - partstracker.redis
      - partstracker.seq